version: '3'
services:
  api_gateway:
    build: "./api_gateway"
    command: uvicorn project.core.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    env_file:
      - ./api_gateway/.env
    depends_on:
      - customers

  customers:
    build: "./customers"
    command: python3 -m project.core.main.py
    ports:
      - "50051:50051"
    env_file:
      - ./customers/.env
    depends_on:
      - consumer_db

  consumer_db:
    image: mongo:5.0.2
    ports:
      - "27018:27018"
    logging:
      driver: none
    volumes:
      - consumer_db:/data/db


volumes:
  consumer_db:
