# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: project/grpc/proto/consumer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!project/grpc/proto/consumer.proto\x12\x08\x63onsumer\x1a\x1bgoogle/protobuf/empty.proto\"\x18\n\nConsumerID\x12\n\n\x02id\x18\x01 \x01(\t\"$\n\x10\x43onsumerUserName\x12\x10\n\x08username\x18\x01 \x01(\t\"L\n\x0e\x43onsumerStatus\x12\x11\n\tis_active\x18\x01 \x01(\x08\x12\x13\n\x0bis_verified\x18\x02 \x01(\x08\x12\x12\n\nstatus_set\x18\x03 \x01(\x08\"\x9e\x01\n\x08\x43onsumer\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x11\n\tfull_name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x17\n\x0fhashed_password\x18\x04 \x01(\t\x12\x12\n\ncreated_at\x18\x05 \x01(\t\x12\x31\n\x0f\x63onsumer_status\x18\x06 \x01(\x0b\x32\x18.consumer.ConsumerStatus\"\x81\x01\n\x0b\x43onsumerOut\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x12\n\ncreated_at\x18\x04 \x01(\t\x12\x31\n\x0f\x63onsumer_status\x18\x05 \x01(\x0b\x32\x18.consumer.ConsumerStatus\"L\n\x0eUpdateConsumer\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x15\n\rnew_full_name\x18\x02 \x01(\t\x12\x11\n\tnew_email\x18\x03 \x01(\t\"x\n\x0cUpdateStatus\x12\x35\n\x11\x63onsumer_username\x18\x01 \x01(\x0b\x32\x1a.consumer.ConsumerUserName\x12\x31\n\x0f\x63onsumer_status\x18\x02 \x01(\x0b\x32\x18.consumer.ConsumerStatus2\x88\x03\n\x07UserAPI\x12\x37\n\x0bGetUserByID\x12\x14.consumer.ConsumerID\x1a\x12.consumer.Consumer\x12\x43\n\x11GetUserByUserName\x12\x1a.consumer.ConsumerUserName\x1a\x12.consumer.Consumer\x12\x37\n\nCreateUser\x12\x12.consumer.Consumer\x1a\x15.consumer.ConsumerOut\x12=\n\nUpdateUser\x12\x18.consumer.UpdateConsumer\x1a\x15.consumer.ConsumerOut\x12\x45\n\x14UpdateConsumerStatus\x12\x16.consumer.UpdateStatus\x1a\x15.consumer.ConsumerOut\x12@\n\nDeleteUser\x12\x1a.consumer.ConsumerUserName\x1a\x16.google.protobuf.Emptyb\x06proto3')



_CONSUMERID = DESCRIPTOR.message_types_by_name['ConsumerID']
_CONSUMERUSERNAME = DESCRIPTOR.message_types_by_name['ConsumerUserName']
_CONSUMERSTATUS = DESCRIPTOR.message_types_by_name['ConsumerStatus']
_CONSUMER = DESCRIPTOR.message_types_by_name['Consumer']
_CONSUMEROUT = DESCRIPTOR.message_types_by_name['ConsumerOut']
_UPDATECONSUMER = DESCRIPTOR.message_types_by_name['UpdateConsumer']
_UPDATESTATUS = DESCRIPTOR.message_types_by_name['UpdateStatus']
ConsumerID = _reflection.GeneratedProtocolMessageType('ConsumerID', (_message.Message,), {
  'DESCRIPTOR' : _CONSUMERID,
  '__module__' : 'project.grpc.proto.consumer_pb2'
  # @@protoc_insertion_point(class_scope:consumer.ConsumerID)
  })
_sym_db.RegisterMessage(ConsumerID)

ConsumerUserName = _reflection.GeneratedProtocolMessageType('ConsumerUserName', (_message.Message,), {
  'DESCRIPTOR' : _CONSUMERUSERNAME,
  '__module__' : 'project.grpc.proto.consumer_pb2'
  # @@protoc_insertion_point(class_scope:consumer.ConsumerUserName)
  })
_sym_db.RegisterMessage(ConsumerUserName)

ConsumerStatus = _reflection.GeneratedProtocolMessageType('ConsumerStatus', (_message.Message,), {
  'DESCRIPTOR' : _CONSUMERSTATUS,
  '__module__' : 'project.grpc.proto.consumer_pb2'
  # @@protoc_insertion_point(class_scope:consumer.ConsumerStatus)
  })
_sym_db.RegisterMessage(ConsumerStatus)

Consumer = _reflection.GeneratedProtocolMessageType('Consumer', (_message.Message,), {
  'DESCRIPTOR' : _CONSUMER,
  '__module__' : 'project.grpc.proto.consumer_pb2'
  # @@protoc_insertion_point(class_scope:consumer.Consumer)
  })
_sym_db.RegisterMessage(Consumer)

ConsumerOut = _reflection.GeneratedProtocolMessageType('ConsumerOut', (_message.Message,), {
  'DESCRIPTOR' : _CONSUMEROUT,
  '__module__' : 'project.grpc.proto.consumer_pb2'
  # @@protoc_insertion_point(class_scope:consumer.ConsumerOut)
  })
_sym_db.RegisterMessage(ConsumerOut)

UpdateConsumer = _reflection.GeneratedProtocolMessageType('UpdateConsumer', (_message.Message,), {
  'DESCRIPTOR' : _UPDATECONSUMER,
  '__module__' : 'project.grpc.proto.consumer_pb2'
  # @@protoc_insertion_point(class_scope:consumer.UpdateConsumer)
  })
_sym_db.RegisterMessage(UpdateConsumer)

UpdateStatus = _reflection.GeneratedProtocolMessageType('UpdateStatus', (_message.Message,), {
  'DESCRIPTOR' : _UPDATESTATUS,
  '__module__' : 'project.grpc.proto.consumer_pb2'
  # @@protoc_insertion_point(class_scope:consumer.UpdateStatus)
  })
_sym_db.RegisterMessage(UpdateStatus)

_USERAPI = DESCRIPTOR.services_by_name['UserAPI']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CONSUMERID._serialized_start=76
  _CONSUMERID._serialized_end=100
  _CONSUMERUSERNAME._serialized_start=102
  _CONSUMERUSERNAME._serialized_end=138
  _CONSUMERSTATUS._serialized_start=140
  _CONSUMERSTATUS._serialized_end=216
  _CONSUMER._serialized_start=219
  _CONSUMER._serialized_end=377
  _CONSUMEROUT._serialized_start=380
  _CONSUMEROUT._serialized_end=509
  _UPDATECONSUMER._serialized_start=511
  _UPDATECONSUMER._serialized_end=587
  _UPDATESTATUS._serialized_start=589
  _UPDATESTATUS._serialized_end=709
  _USERAPI._serialized_start=712
  _USERAPI._serialized_end=1104
# @@protoc_insertion_point(module_scope)
